apiVersion: v1
kind: Service
metadata:
  labels:
    tier: content-server
  name: content-server
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    tier: content-server
  type: NodePort
