apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-server
  labels:
    tier: content-server
    app: si
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: content-server
  template:
    metadata:
      labels:
        tier: content-server
    spec:
      containers:
        - name: content-server
          image: andreytamplon/content_server:1.1
          envFrom:
            - configMapRef:
                name: content-config
          ports:
            - containerPort: 8084
              protocol: TCP