apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    tier: frontend
    app: si
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: andreytamplon/frontend:1.5
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 80
              protocol: TCP
