kind: PersistentVolume
apiVersion: v1
metadata:
  name: authdb-pv-volume
  labels:
    type: local
    app: authdb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/auth_volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authdb-pv-claim
  labels:
    app: authdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

