apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    tier: auth-server
    app: si
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: auth-server
  template:
    metadata:
      labels:
        tier: auth-server
    spec:
      containers:
        - name: auth-server
          image: andreytamplon/auth_server:1.1
          envFrom:
            - configMapRef:
                name: auth-config
          ports:
            - containerPort: 8085
              protocol: TCP
