apiVersion: v1
kind: Service
metadata:
  labels:
    tier: auth-server
  name: auth-server
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
  selector:
    tier: auth-server
  type: NodePort
