apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contentdb
  template:
    metadata:
      labels:
        app: contentdb
    spec:
      containers:
        - name: contentdb
          image: postgres:14.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: contentdb-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: contentdb
      volumes:
        - name: contentdb
          persistentVolumeClaim:
            claimName: contentdb-pv-claim