kind: PersistentVolume
apiVersion: v1
metadata:
  name: contentdb-pv-volume
  labels:
    type: local
    app: contentdb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/content_volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: contentdb-pv-claim
  labels:
    app: contentdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

